# -*- coding: utf-8 -*-
"""def function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cdv8doyiCRdwaCDLl-ocS9UN1iNWLkV

##### Question 1:
##### Define a class named Car with attributes make, model, and year.
##### Include a method called get_info() that prints out the details of the car.
##### Create an instance of the Car class and call the get_info() method.
"""

class car:
  def __init__(self,make,model,year):
    self.make=make
    self.model=model
    self.year=year
  def get_info(self):
    print(f"{self.make},{self.model},{self.year}")

car1=(car("totyota","Corolla", 2020))
car1.get_info()

car1=car("honda","car",2021)
car1.get_info()

"""##### Question 2:
##### Create a class named Rectangle with attributes length and width.
##### Include methods to calculate the area and perimeter of the rectangle.
#####  Create an instance of the Rectangle class with length 5 and width 3, then print its area and perimeter.
"""

class rectangle:
  def __init__(self,length,width):
    self.length=length
    self.width=width

  def area(self):
   return self.length*self.width


  def perimeter(self):
    return 2*(self.length + self.width)


rect = rectangle(5,3)
print("area",rect.area())
print("perimeter",rect.perimeter())

"""##### Question 3:
##### Define a class called Employee with attributes name, position, and salary.
##### Include a method called raise_salary() that takes a percentage increase as an argument and updates the salary accordingly.
##### Create an instance of the Employee class and call the raise_salary() method with a 10% increase
"""

class employee:
  def __init__ (self,name,position,salary):
   self.name =name
   self.position = position
   self.salary = salary

  def raise_salary(self,percent):
    self.salary +=self.salary * (percent / 100)

emp= employee("sakshi","devloper",50000)
emp.raise_salary(10)
print(emp.salary)

"""##### Question 4:
##### Create a class named BankAccount with attributes account_number, holder_name, and balance.
##### Include methods to deposit money, withdraw money, and check the balance.
##### Create an instance of the BankAccount class, deposit $100, withdraw $50, and then print the remaining balance.

"""

class BankAcc:
  def __init__ (self,acc_num,holder_name,balance):
    self.acc_num=acc_num
    self.holder_name=holder_name
    self.balance =balance

  def deposit(self,amount):
    self.balance += amount
    return self.balance

  def withdraw(self,amount):
    self.balance -= amount
    return self.balance

  def check_balance(self):
    return self.balance

acc =BankAcc(1234,"sakshi",30000)
acc.deposit(100)
acc.withdraw(50)
print("Remaining balance :", acc.check_balance())

"""##### Question 5:
##### Define a class named Circle with attributes radius and color.
##### Include methods to calculate the area and circumference of the circle.
##### Create an instance of the Circle class with radius 5 and color "blue", then print its area and circumference.
"""

import math
class circle:
  def __init__ (self,radius,color):
    self.radius=radius
    self.color=color

  def area(self):
    return math.pi * self.radius ** 2

  def circumference(self):
    return 2 * math.pi * self.radius

c=circle(6,"blue")
print("area :-",c.area())
print("circumference :-",c.circumference())

"""##### Question 6:
##### Create a class named Book with attributes title, author, and price.
##### Include a method called discount() that takes a percentage discount as an argument and updates the price accordingly.
##### Create an instance of the Book class and call the discount() method with a 20% discount.
"""

class book:
  def __init__ (self,title,author,price):
    self.title=title
    self.author=author
    self.price=price

  def discount(self,percent):
    self.price-=self.price  * (percent/100)

b=book("Python Basics", "John Doe",1500)
b.discount(10)
print("discounted price",b.price)

"""##### Question 7:
##### Define a class called Student with attributes name, age, and grades.
##### Include a method called calculate_average() that computes the average grade of the student.
##### Create an instance of the Student class with name "Alice", age 20, and grades [90, 85, 88], then print the average grade.
"""

class student:
  def __init__ (self,name,age,grades):
    self.name=name
    self.age=age
    self.grades=grades

  def calculate_avg(self):
    return sum(self.grades)/len(self.grades)

s=student("sakshi",22,[90,85,70])
print("avg_calc",s.calculate_avg())

"""##### Question 10:
##### Create a class named BankAccount with attributes account_number, account_holder, and balance.
##### Include methods to deposit and withdraw money, and to display the account details.
##### Create two instances of the BankAccount class, one for a savings account and one for a checking account, and perform deposit and withdrawal operations on each.
"""

class BankAcc:
  def __init__ (self,acc_num,holder_name,balance):
    self.acc_num=acc_num
    self.holder_name=holder_name
    self.balance =balance

  def deposit(self,amount):
    self.balance += amount
    return self.balance

  def withdraw(self,amount):
    self.balance -= amount
    return self.balance

  def check_balance(self):
    return self.balance

acc =BankAcc(1234,"sakshi",30000)
acc.deposit(100)
acc.withdraw(50)
print("Remaining balance :", acc.check_balance())

"""##### Question 13:
##### Define a class called Triangle with attributes side1, side2, and side3.
##### Include methods to check if the triangle is valid, calculate its perimeter, area, and display its sides.
##### Create an instance of the Triangle class with side lengths 3, 4, and 5, then check if it is valid, calculate its perimeter and area, and display its sides.
"""

import math

class Triangle:
    def __init__(self, side1, side2, side3):
        self.side1 = side1
        self.side2 = side2
        self.side3 = side3

    def is_valid(self):
        return (self.side1 + self.side2 > self.side3 and
                self.side2 + self.side3 > self.side1 and
                self.side1 + self.side3 > self.side2)

    def perimeter(self):
        return self.side1 + self.side2 + self.side3

    def area(self):
        s = self.perimeter() / 2
        return math.sqrt(s * (s - self.side1) * (s - self.side2) * (s - self.side3))

    def display_sides(self):
        print(f"Sides: {self.side1}, {self.side2}, {self.side3}")

triangle = Triangle(3, 4, 5)

print("Is Valid:", triangle.is_valid())
print("Perimeter:", triangle.perimeter())
print("Area:", triangle.area())
triangle.display_sides()