# -*- coding: utf-8 -*-
"""list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czhsu-yZhWJWMnNiNk7Tkvrijzb0o2IM

***1- Write a program to access the third element from the given list.***
"""

lst = [10, 20, 30, 40, 50]
lst[2]

"""***2 Write a program to access the last element from the given list using negative indexing.***"""

lst = ['apple', 'banana', 'cherry', 'date']
lst[-1]

"""***3 Write a program to change the second element to 100 in the given list.***"""

lst = [5, 10, 15, 20, 25]
lst[1] = 100
print(lst)

"""***4 Write a program to access the first element using negative indexing.***"""

lst = [7, 14, 21, 28, 35]
lst[-5]

"""***5 Write a program to access the second last element from the given list.***"""

lst = [1, 2, 3, 4, 5, 6]
lst[-2]

"""***6 Write a program to extract the first three elements from the given list.***"""

lst = [100, 200, 300, 400, 500, 600]
lst[:3]

"""***7 Write a program to extract all elements except the first two from the given list.***"""

lst = [2, 4, 6, 8, 10, 12]
lst[2:]

"""***8 Write a program to extract every alternate element from the given list.***"""

lst = [5, 10, 15, 20, 25, 30, 35]
lst[::2]

"""***9 Write a program to reverse the given list using slicing.***"""

lst = [1, 3, 5, 7, 9]
lst[::-1]

"""***10 Write a program to extract elements from index 2 to 5 from the given list.***"""

lst = [11, 22, 33, 44, 55, 66, 77]
lst[2:6]

"""***11 Write a program to access the second element from the first nested list.***"""

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst[0][1]

"""***12 Write a program to extract the last element from the last nested list.***"""

lst = [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
lst[-1][-1]

"""***13 Write a program to extract the second and third lists from a given nested list***"""

lst = [[10, 20], [30, 40], [50, 60], [70, 80]]
lst[1:3]

"""***14 Write a program to extract the second element from all nested lists.***"""

lst = [[1, 9], [2, 8], [3, 7], [4, 6]]
output = [sub[1] for sub in lst]
print(output)

"""***15 Write a program to reverse all sublists in a nested list.***"""

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
output = [sub[::-1] for sub in lst]
print(output)

"""###APPEND

***1- Write a program to append the number 100 to the given list.***
"""

lst = [10, 20, 30, 40]
lst.append(100)
print(lst)

"""***2 Write a program to append a string "Hello" to the given list.***"""

lst =['apple', 'banana', 'cherry']
lst.append('Hello')
print(lst)

"""***3 Write a program to append a list [5, 6, 7] as a single element in the given list.***"""

lst = [1, 2, 3, 4]
lst.append([5,4,6])
print(lst)

"""***4 Write a program to extend the given list by adding another list [50, 60, 70].***"""

lst = [10, 20, 30, 40]
lst.extend([50, 60, 70])
print(lst)

"""***5 Write a program to extend a list of numbers [7, 8, 9] with another list [10, 11, 12].***"""

lst = [10, 20, 30, 40]
lst.extend([10, 11, 12])
print(lst)

"""***6 Write a program to extend a list of strings ["cat", "dog"] with another list ["lion", "tiger"].***"""

lst = ["cat", "dog"]
lst.extend(["lion", "tiger"])
print(lst)

"""###pop() Function Questions

***7 Write a program to remove the last element from the given list using the pop function.***
"""

lst = [10, 20, 30, 40]
lst.pop()
print(lst)

"""***8 Write a program to remove the third element from the given list using the pop function.***"""

lst =  [1, 2, 3, 4, 5]
lst.pop(2)
print(lst)

"""***9 Write a program to remove the first element from the given list using the pop function.***"""

lst = [100, 200, 300, 400]
lst.pop(0)
print(lst)

"""###remove() Function Questions

***10 Write a program to remove the element 20 from the given list.***
"""

lst =[10, 20, 30, 40, 50]
lst.remove(20)
print(lst)

"""***11 Write a program to remove the first occurrence of "apple" from the given list.***"""

lst =["banana", "apple", "cherry", "apple"]
lst.remove("apple")
print(lst)

"""***12 Write a program to remove the number 5 from the given list if it exists.***"""

lst =[1, 2, 3, 4, 5, 6]
lst.remove(5)
print(lst)

"""###index() Function Questions ###

***13 Write a program to find the index of the element 50 in the given list.***
"""

lst =[10, 20, 30, 40, 50, 60]
lst.index(50)

"""***14 Write a program to find the index of "cherry" in the given list.***"""

lst = ["apple", "banana", "cherry", "date"]
lst.index("cherry")

"""***15 Write a program to find the index of the number 100 in the given list. If not found, print "Not found"***"""

lst = [10, 20, 30, 40]
if 100 in lst:
    print(lst.index(100))
else:
    print("Not found")

"""### count() Function Questions ###

***16 Write a program to count the occurrences of 5 in the given list.***
"""

lst = [1, 5, 2, 5, 3, 5, 4]
lst.count(5)

"""***17 Write a program to count how many times "apple" appears in the given list***"""

lst =["apple", "banana", "apple", "cherry", "apple"]
lst.count("apple")

"""***18 Write a program to count the occurrences of 100 in the given list.***"""

lst = [10, 20, 30, 40, 50]
lst.count(100)

"""### min() and max() Function Questions ###

***19 Write a program to find the minimum value in the given list.***
"""

lst = [45, 12, 78, 34, 23]
min(lst)

"""***20 Write a program to find the maximum value in the given list.***"""

lst =[99, 55, 73, 21, 64]
max(lst)