# -*- coding: utf-8 -*-
"""Loops Assi.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqvfZMvhxANklN7XtRZyJyK3fuQvXJf5

#### 1.	Given a list [4, 8, 2, 10, 6], find the maximum number using a for loop.
"""

nums = [4, 8, 2, 10, 6]
max_num = nums[0]
for n in nums:
    if n > max_num:
        max_num = n
print(max_num)

"""#### 2.	Take input from the user and find the factorial of the number using a for loop"""

num = int(input("Enter the num ="))
fact = 1
for i in range (1,num + 1):
  fact *= i
print(fact)

"""#### 3.	Given a list ['apple', 'banana', 'cherry', 'date', 'fig'], print each element along with its index using a for loop."""

fruits = ['apple', 'banana', 'cherry', 'date', 'fig']

for i in range(len(fruits)):
    print(i, fruits[i])

"""#### 4.	Take a string input from the user and count the number of uppercase letters using a for loop. (Use char.isupper())"""

text = input("Enter string: ")
count = 0

for ch in text:
    if ch.isupper():
        count += 1

print(count)

"""#### 5.	Given a list of integers [17, 25, 39, 42, 58, 71, 86, 93], find the sum of all the even numbers using a for loop."""

nums = [17, 25, 32, 42, 58, 71, 86, 93]
total = 0

for n in nums:
    if n % 2 == 0:
        total += n

print(total)

"""#### 6.	Given a list [3, 6, 9, 12, 15], calculate the product of all the elements using a for loop."""

num =[3, 6, 9, 12, 15]
product =1
for n in num:
  product *= n
  print(product)

"""#### 7.	Given a list [2, 3, 5, 7, 11, 13, 17, 19], find the index of the first occurrence of the number 7 using a for loop."""

nums=[2, 3, 5, 7, 11, 13, 17, 19]
for i in range(len(nums)):
    if nums[i] == 7:
        print(i)
        break

"""#### 8.	Take a string input from the user and reverse it using a for loop."""

s = input("Enter the string =")
rev ="  "
for ch in s:
  rev = ch + rev
print(rev)

"""#### 9.	Given a list [10, 20, 30, 40, 50], print each element multiplied by 2 using a for loop."""

num=[10, 20, 30, 40, 50]
for i in num:
  print(i*2)

"""#### 10.	Given a list of words ['Python', 'Java', 'C++', 'JavaScript', 'Ruby'], find the longest word using a for loop."""

words = ['Python', 'Java', 'C++', 'Javascript', 'Ruby']
longest = words[0]

for w in words:
    if len(w) > len(longest):
        longest = w

print(longest)

"""#### 11.	Take a string input from the user and count the number of vowels using a for loop. (Vowels: a, e, i, o, u)"""

string = input("Enter a string: ")
vowels = "aeiouAEIOU"
count = 0
for char in string:
    if char in vowels:
        count += 1
print("Number of vowels:", count)

"""#### 12.	Given a list of integers [4, 9, 16, 25, 36], print the square root of each number using a for loop."""

numbers = [4, 9, 16, 25, 36]
for num in numbers:
    print(num ** 0.5)

"""#### 13.	Given a list [1, 3, 5, 7, 9, 11], check if a user-inputted number is present in the list using a for loop.

"""

numbers = [1, 3, 5, 7, 9, 11]
user = int(input("Enter a number: "))
found = False
for num in numbers:
    if num == user:
        found = True
        break
if found:
    print("Number is in the list")
else:
    print("Number is NOT in the list")

"""#### 14.	Given a list [100, 200, 150, 50, 75], find the minimum number using a for loop"""

numbers = [100, 200, 150, 50, 75]

minimum = numbers[0]

for num in numbers:
    if num < minimum:
        minimum = num

print("Minimum number:", minimum)

"""#### 15.	Take a sentence as input from the user and count the number of words using a for loop. (Words are separated by spaces.)"""

sentence = input("Enter a sentence: ")
count = 1

for char in sentence:
    if char == " ":
        count += 1

print("Number of words:", count)

"""#### 16.	Given a list [20, 40, 60, 80, 100], create a new list with elements divided by 10 using a for loop"""

numbers = [20, 40, 60, 80, 100]
new_list = []

for num in numbers:
    new_list.append(num / 10)

print(new_list)

"""#### 17.	Given a list ['red', 'green', 'blue', 'yellow', 'purple'], print only the words that have more than 4 letters using a for loop."""

colors = ['red', 'green', 'blue', 'yellow', 'purple']

for word in colors:
    if len(word) > 4:
        print(word)

"""#### 18.	Take a number as input from the user and generate a list of its multiplication table up to 10 using a for loop."""

num = int(input("Enter a number: "))
table = []

for i in range(1, 11):
    table.append(num * i)

print(table)

"""#### 19.	Given a dictionary {'A': 10, 'B': 20, 'C': 30, 'D': 40}, print all key-value pairs using a for loop."""

data = {'A': 10, 'B': 20, 'C': 30, 'D': 40}

for key in data:
    print(key, ":", data[key])

"""#### 20.	Given a list of mixed values [1, 'hello', 3.5, 'world', 10, 'Python'], print only the integer values using a for loop."""

items = [1, 'hello', 3.5, 'world', 10, 'Python']
for item in items:
    if type(item) == int:
        print(item)