# -*- coding: utf-8 -*-
"""Operators assi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fd--7HHKCV93GCgb9pYTowZR81PnX4Xq

***Write a Python program to take two numbers as input from the user and display their sum.***
"""

num1=int(input("Enter the number="))
num2=int(input("Enter the number="))
sum=num1+num2
print(sum)

"""***Calculate and print the midpoint of two numbers entered by the user.***


"""

num1=float(input("Enter the number="))
num2=float(input("Enter the number="))
midpoint=num1+num2/2
print(midpoint)

"""***Write a Python program to calculate the area of a triangle using the formula: area = 0.5 * base * height.***


"""

base=float(input("Enter base of triangle = "))
height=float(input("Enter height of triangle = "))
area=0.5*base*height
print(area)

"""***Take three numbers as input from the user and display their product.***


"""

x=float(input("Enter the 1st num ="))
y=float(input("Enter the 2nd num ="))
z=float(input("Enter the 3rd num ="))
product = x * y * z
print(product)

"""***Take a number as input and display its square and cube.***

"""

a=float(input("Enter the num = "))
print("Square :",a**2)
print("cube :",a**3)

"""***Take two numbers as input and display their quotient and remainder.***


"""

a=float(input("Enter the num = "))
b=float(input("Enter the num = "))
print("quotient:",a // b)
print("reminder :",a % b)

"""***Take three numbers as input and display their average.***

"""

x=float(input("Enter the 1st num ="))
y=float(input("Enter the 2nd num ="))
z=float(input("Enter the 3rd num ="))
average=(x+y+z)/3
print(average)

"""***Write a Python program to calculate the area of a rectangle using the formula: area = length * width.***

"""

length=float(input("Enter the length ="))
width=float(input("Enter the width ="))
area=length * width
print(area)

"""***Take five numbers as input representing marks obtained and total marks.
Display the percentage.***

"""

a=float(input("Enter the obtained marks = "))
b=float(input("Enter the total marks = "))
percentage=(a/b)*100
print(percentage)

"""***Write a Python program to swap two numbers entered by the user without using a third variable.***

"""

a = float(input("Enter first number= "))
b = float(input("Enter second number= "))
a, b = b, a
print("swapping: a =", a, ", b =", b)

"""***Take a number as input and check whether it is even or odd.***"""

a = int(input("Enter a number: "))
if a % 2 == 0:
    print("Even number")
else:
    print("Odd number")

"""***Write a Python program to convert temperature from Celsius to Fahrenheit using the formula: F = (C × 9/5) + 32.***

"""

celsius = float(input("Enter the Celsius = "))
fahrenheit = (celsius * 9/5) + 32
print(fahrenheit)

"""***Write a Python program to convert temperature from Fahrenheit to Celsius using the formula: C = (F - 32) × 5/9.***

"""

fahrenheit=float(input("Enter the fahrenheit = "))
celsius=(fahrenheit-32)*5/9
print(celsius)