# -*- coding: utf-8 -*-
"""Strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Stoo6V4luLhUK55s4oele-fbHvWLYwjb

Q1 Write a Python program that accepts a string from user. Your program should create and display a new string where the first and last characters have been exchanged.

For example if the user enters the string 'HELLO' then new string would be 'OELLH'
"""

string= input("Enter a String =")
first = string[0]
last= string[-1]
mid = string [1 : -1]
print(last + mid + first)

"""Q2 Write a Python program that accepts a string from user. Your program should create a new string in reverse of first string and display it.

For example if the user enters the string 'EXAM' then new string would be 'MAXE'
"""

s=input("Enter a String =")
print(s[-1: :-1])

"""Q3 Write a Python program that accepts a string from user. Your program should create a new string by shifting one position to left.

For example if the user enters the string 'examination 2021' then new string would be 'xamination 2021e'
"""

s=input("Enter a String =")
n=s[1:]+s[0]
print(n)

"""Q4 Write a Python program to calculate the length of a string."""

s=input("Enter a String =")
a=len(s)
print(a)

"""Q5 Write a Python program to get a string made of the first 2 and last 2 characters of a given string. If the string length is less than 2, return the empty string instead.
Sample String : 'w3resource'
Expected Result : 'w3ce'
Sample String : 'w3'
Expected Result : 'w3w3'
Sample String : ' w'
Expected Result : Empty String
"""

s=input("Enter a String =")
first=s[0:2]
Last=s[-2:]
print(first + Last)

"""Q6 Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string already ends with 'ing', add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged.
Sample String : 'abc'
Expected Result : 'abcing'
Sample String : 'string'
Expected Result : 'stringly'
"""

str=input("Enter the String =")
if len(str) < 3:
  result=str
elif str.endswith('ing'):
  result = str + 'ly'
else:
    result = str + 'ing'
print( result)

"""Q7 Write a Python program to remove the nth index character from a nonempty string."""

s=str = input("Enter the String = ")
n=int(input("Enter the character remove = "))
str2=str[:n] + str[n+1:]
print(str2)

"""Q8 Write a Python program to change a given string to a newly string where the first and last chars have been exchanged."""

s=input("Enter the String = ")
if len(s) <= 1 :
  a=s
else :
  a=s[-1] + s[1:-1] + s[0]
print(a)

"""Q9 Write a Python script that takes input from the user and displays that in upper and lower cases."""

s=input("Enter the string =")
l=s.lower()
u=s.upper()
print(u)
print(l)